name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认：<br>
Please verify that you've followed these steps:
"
      options:
        - label: "
我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br>
I have searched on the [issue tracker](……/) for a related feature request.
"
          required: true
        - label: "
我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/CDTP/blob/master/README_CN.md) 并无法自行解决问题。
I have read the [documentation](https://github.com/ZhuYanzhen1/CDTP/blob/master/README.md) and was unable to solve the issue.
"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: "请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？目前 CDTP 的行为是什么？<br>
      Please express your statement in detail and clearly. For example, how does this problem affect you? What do you want to achieve? What is the current behavior of CDTP?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Solution
      description: "
此项非必须，但是如果你有想法的话欢迎提出。<br>
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change
"
